[versions]

kotlinx-coroutines = "1.8.1"
aqueue = "1.0.10"

[libraries]

kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
aqueue = { module = "me.y9san9.aqueue:core", version.ref = "aqueue" }
